//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExplorerSwitch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExplorerSwitch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer context menu switcher for Windows 11.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use classic menu.
        /// </summary>
        public static string ButtonClassicMenu_Content {
            get {
                return ResourceManager.GetString("ButtonClassicMenu.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use new menu.
        /// </summary>
        public static string ButtonNewMenu_Content {
            get {
                return ResourceManager.GetString("ButtonNewMenu.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic context menu.
        /// </summary>
        public static string Classic_context_menu {
            get {
                return ResourceManager.GetString("Classic_context_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer context menu switch.
        /// </summary>
        public static string GroupBox_Header {
            get {
                return ResourceManager.GetString("GroupBox.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic context menu.
        /// </summary>
        public static string MainWindow_SetCurrentMode_Classic_context_menu {
            get {
                return ResourceManager.GetString("MainWindow_SetCurrentMode_Classic_context_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern context menu.
        /// </summary>
        public static string MainWindow_SetCurrentMode_Modern_context_menu {
            get {
                return ResourceManager.GetString("MainWindow_SetCurrentMode_Modern_context_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart computer to apply the changes..
        /// </summary>
        public static string MainWindow_ShowMessage_Please_restart_computer_to_apply_the_changes_ {
            get {
                return ResourceManager.GetString("MainWindow_ShowMessage_Please_restart_computer_to_apply_the_changes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switched.
        /// </summary>
        public static string MainWindow_ShowMessage_Switched {
            get {
                return ResourceManager.GetString("MainWindow_ShowMessage_Switched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern context menu.
        /// </summary>
        public static string Modern_context_menu {
            get {
                return ResourceManager.GetString("Modern_context_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current mode: .
        /// </summary>
        public static string TextBlockCurrentModeLabel_Text {
            get {
                return ResourceManager.GetString("TextBlockCurrentModeLabel.Text", resourceCulture);
            }
        }
    }
}
